const emotionalStates = [
  { description: "Eres un idiota y tratas de justificar tu ignorancia.", title: "neutral", id: 0 },
  { description: "Ya veo... ¿así que la gente está adivinando?", title: "neutral", id: 1 },
  { description: "[NAME] es tan inmaduro.", title: "neutral", id: 2 },
  { description: "He perdido por completo mi voz en este período. Esto ha sido una locura 11 minutos de juego", title: "neutral", id: 3 },
  { description: '"Te ves un poco mayor sin la ropa puesta" - [NOMBRE]', title: "neutral", id: 4 },
  { description: "¿Qué demonios?", title: "ira", id: 5 },
  { description: "Qué herramienta más inútil.", title: "ira", id: 6 },
  { description: "¿Qué demonios?", title: "ira", id: 7 },
  {
    description: "facetune es un trabajo duro, maldito poro. Trabajo todo el día para mantener a esta familia, ¿y este es el agradecimiento que recibo?",
    title: "ira",
    id: 8,
  },
  { description: "Tengo que descargar esta mierda de alguna manera.", title: "ira", id: 9 },
  { description: "Esto es aterrador. Buena suerte a ti y a tu familia. Espero que descubran quiénes son las enrevesadas muy pronto.", title: "miedo", id: 10 },
  { description: "Esa arena es tan fea que yo también tendría miedo.", title: "miedo", id: 11 },
  { description: "Bastante aterrador. Imagina si fueras a un viaje escolar, no hicieras nada, y volvieras a casa a esto.", title: "miedo", id: 12 },
  { description: "Estoy a punto de tener un ataque al corazón esta noche", title: "miedo", id: 13 },
  { description: "¡Qué increíblemente peligroso!", title: "miedo", id: 14 },
  { description: "Este control de impulso por parte de los árbitros nos está matando, y lo estamos dejando", title: "agresividad", id: 15 },
  { description: "Lol Sólo estoy jodiendo Puedo esperar", title: "agresividad", id: 16 },
  { description: "Pero literalmente lo tenía. Su nombre en él. Los niños son tan estúpidos.", title: "agresividad", id: 17 },
  {
    description: 'AV es un sistema en el que si votas por un perdedor puedes cambiar de opinión y "tener otra oportunidad". Ese es el problema.',
    title: "agresividad",
    id: 18,
  },
  { description: "Detente. ¿Cómo puedes ver [NAME] estos últimos años y pensar que le quedan 2-3 años?", title: "agresividad", id: 19 },
  { description: "Dios mío, pensé lo mismo.", title: "sorpresa", id: 20 },
  { description: "las enmiendas se permiten el lunes para el acuerdo de mayo, me sorprendería si nadie mata su acuerdo", title: "sorpresa", id: 21 },
  { description: "¡He estado comiendo avavodos mal todo este tiempo! ¡Oh, no!", title: "sorpresa", id: 22 },
  { description: "Oh. Nunca había oído eso antes.", title: "sorpresa", id: 23 },
  { description: "Oh wow, no me di cuenta de eso.", title: "sorpresa", id: 24 },
  { description: "No dejes que unos meses difíciles se interpongan en el camino de un posible futuro hermoso.", title: "optimismo", id: 25 },
  { description: "Tengo que eliminar la competencia. Es sólo un buen negocio.", title: "optimismo", id: 26 },
  { description: "Nunca pre-ordeno nada y nunca me decepciona esa decisión.", title: "optimismo", id: 27 },
  { description: "Mauston y Monticello fueron el principio y el fin de mi esperanza", title: "optimismo", id: 28 },
  { description: "Eso es imprudente. Tiene suerte de que no se desfigurara o matara de forma permanente.", title: "optimismo", id: 29 },
  { description: "El juego ND vs Georgia en Atenas será bueno.", title: "admiración", id: 30 },
  { description: "¡Bonito silbido!", title: "admiracion", id: 31 },
  { description: "Muy bien, jurando una tormenta justo delante de tus hijos.", title: "admiracion", id: 32 },
  { description: "Maravillosos esculturas. Me encanta la expresión de la mitología escocesa detrás de ellos.", title: "admiracion", id: 33 },
  { description: "Salud, amigo. ¡Votado!", title: "admiracion", id: 34 },
  { description: "¿Por qué se ven como sus máscaras de gas?", title: "distracion", id: 35 },
  {
    description:
      "Siento la pregunta tonta, pero ¿de dónde sacan la señal los buscapersonas? ¿Todavía hay un emisor alrededor o torres de telefonía móvil este trabajo ahora?",
    title: "distracion",
    id: 36,
  },
  { description: "Podrían ser dos personas en su teléfono. Supongo que tenían luz verde en ese momento.", title: "distracion", id: 37 },
  { description: "Si están sufriendo un dolor inmenso, dudo que ver Endgame sea lo más importante en su lista de prioridades.", title: "distracion", id: 38 },
  { description: "Esto me pasó hace 6 meses y todavía estoy herido y activamente tratando de hablar con ella... Idk cómo parar", title: "distracion", id: 39 },
  { description: "Tan feliz por [NAME]. Es tan triste que no esté aquí. Imagínese este equipo con [NAME] en lugar de [NAME]. Ugh.", title: "alegria", id: 40 },
  {
    description:
      "Eso tiene algunas implicaciones divertidamente desafortunadas para aquellos que creen que todos [NAME] son descendientes de [NAME], hijo de [NAME] y [NAME]. ",
    title: "alegria",
    id: 41,
  },
  { description: "Me complace recibir consejos constructivos. Si alguien es corto, o no constructivo, reaccionaré a ello.", title: "alegria", id: 42 },
  { description: "¿Lol publicarlo en mi historia? Sí, esperaba un montón de odio de mi post XD. Mis amigos me conocen.", title: "alegria", id: 43 },
  { description: "Oh, no, el concierto se acabó. Realmente soy [NAME]. LOL", title: "alegria", id: 44 },
  { description: "Me encantaría ponerme musculoso accidentalmente... En lugar de trabajar mi culo para perder grasa en este momento.", title: "amor", id: 45 },
  { description: "¡Amarás a la gente feliz! Perfecto para ver cuando estás nevado.", title: "amor", id: 46 },
  { description: "Enviando tu amor", title: "amor", id: 47 },
  { description: "Es posible que desee investigar la terapia", title: "amor", id: 48 },
  { description: "Me encantó caer de la grieta en el techo y salir en un resplandor de gloria.", title: "amor", id: 49 },
  {
    description: "Y mis disculpas si mal interpreté pero usted parecía decir varias veces que le impide buscar a otras mujeres, como el ejemplo de [NAME].",
    title: "remordimiento",
    id: 50,
  },
  {
    description: "Quiropráctica es sólo una estafa de todos modos, un montón de estudios demostrado que no tiene ningún efecto, lo siento que te pasó btw. ",
    title: "remordimiento",
    id: 51,
  },
  { description: "Siento haberme burlado de su nombre de usuario, me disculpo sinceramente.", title: "remordimiento", id: 52 },
  {
    description: "Me da un poco de vergüenza decir que pensé que eso era lo que el título implicaba también. Me alegra que no sea así.",
    title: "remordimiento",
    id: 53,
  },
  {
    description: "Oh, lo entiendo, eres analfabeto a propósito porque temes ser alimentado con mentiras (en tu mente). Lo siento por ti.",
    title: "remordimiento",
    id: 54,
  },
  {
    description: "Oh, no me di cuenta de que estabas diciendo eso, mi error. Y sí, esa es una gran idea que le ayudaría a desarrollarlo. ",
    title: "confianza",
    id: 55,
  },
  {
    description:
      "No se puede jugar a la defensa cuando todo es llamada y por otro lado los Bulls no han recibido una llamada desde principios del trimestre...",
    title: "confianza",
    id: 56,
  },
  {
    description: "¡Descubrí este canal anoche! Ella tiene un video sobre Harry Potter y el final de la historia que es realmente bueno.",
    title: "confianza",
    id: 57,
  },
  { description: "De vez en cuando nos despertamos de nuestras rutinas y nos preguntamos si todavía estamos vivos.", title: "confianza", id: 58 },
  {
    description:
      "Mi esperanza también se ha ido. Suena como si ambos lo hubiéramos intentado una y otra vez, y otra vez. ¿Cuándo te golpearon las realizaciones?",
    title: "confianza",
    id: 59,
  },
  { description: "Ese es mi insulto favorito nunca", title: "decepcion", id: 60 },
  { description: "yo como el carajo", title: "decepcion", id: 61 },
  { description: "Sí, no puedo ni en el móvil, lo mismo con suficiente internet. Completamente decepcionante.", title: "decepcion", id: 62 },
  { description: "Nuestro caballero de brillante armadura. Extrañaré esos calcetines altos.", title: "decepcion", id: 63 },
  { description: "Vaya. Pensé que los antivaxxers no podían bajar. El chico estaba muy equivocado.", title: "decepcion", id: 64 },
  { description: "En realidad siento pena por ella. Ella tiene depresión y baja autoestima, esto no va a hacerlo mejor.", title: "pena", id: 65 },
  { description: "Hoy escucharé la muerte y la destrucción.", title: "pena", id: 66 },
  { description: "Nunca has jugado contra un buen apoyo [NAME] entonces", title: "pena", id: 67 },
  { description: "RIP [NAME], eras una chica dulce. Han pasado más de 10 años pero todavía te echo de menos.", title: "pena", id: 68 },
  { description: "Estoy quebrado, lidiando con mi propia enfermedad mental, e inmediatamente preocupado por mantener la paz.", title: "pena", id: 69 },
  {
    description: "Hermano que nos destruyeron la última vez, estamos a punto de un desgarrador objetivo de campo perdido o muy mal tiempo de rotación ",
    title: "tristeza",
    id: 70,
  },
  { description: "Qué pena, no lo sabía.", title: "tristeza", id: 71 },
  { description: "Sí, nadie quiere creer mi religión y cómo hacer feliz a la gente para que me entristezca.", title: "tristeza", id: 72 },
  {
    description: 'Ese "trabajo duro" usualmente involucraba a la basura presionando Q así que no estoy a punto de derramar lágrimas.',
    title: "tristeza",
    id: 73,
  },
  { description: "Pero todo lo que esto hace es lastimar a la persona promedio no la manera correcta de recaudar dinero.", title: "tristeza", id: 74 },
  {
    description:
      "Sólo curiosidad, ¿por qué iba a importar eso? Actuar es jugar un papel, así que ¿cómo es importante que el personaje y el actor coincidan las orientaciones? ",
    title: "interes",
    id: 75,
  },
  { description: "¿A qué hora se van todos mañana?", title: "interes", id: 76 },
  { description: "Realmente quiero saber qué restaurante es este. Me estoy imaginando a Fino por alguna razón.", title: "interes", id: 77 },
  { description: "Lo sé [NAME]. Ella no es tan genial. Y sabes que su marido está en una silla de ruedas, ¿verdad?", title: "interes", id: 78 },
  { description: "¿Decir qué? No entiendo la broma, ¿es el fundador del MLM? ¿Estás hablando de sexo o financieramente?", title: "interes", id: 79 },
  { description: "Ooh! Ooh! ¡Quiero perder más de 5-10 libras de vanidad! (... guiño guiño guiño)", title: "extasis", id: 80 },
  { description: "No puedo esperar a que mamá le abofetee la mano.", title: "extasis", id: 81 },
  { description: "¡Sí! ¡Amigos engreídos!", title: "extasis", id: 82 },
  { description: "¡Emocionados por estar ahí, chicos! ¡Los veo allí!", title: "extasis", id: 83 },
  { description: "Pagaría una buena moneda por leer esa historia de amor.", title: "extasis", id: 84 },
  { description: "Sí, como sea que lo deletrees - Yo no juego con ellos ", title: "asombro", id: 85 },
  { description: "Prefiero no estar en la categoría de niños de los 90 de todos modos.", title: "asombro", id: 86 },
  { description: "No sé por qué se lo tomaba así, se había ido tanto tiempo así que alguien iba a hacer un espectáculo así.", title: "asombro", id: 87 },
  { description: "¡Mierda, mierda, mega mierda!", title: "asombro", id: 88 },
  { description: "Ganaron VEGAS no el QUALIFIER PRO LEAGUE. Deja de intentar provocarme.", title: "asombro", id: 89 },
  { description: "Yo no le diría nada, ese maldito bicho raro nunca vería a mi hijo. Fin. Asqueroso.", title: "asco", id: 90 },
  { description: "Vuelve al ala. Parece horrible en esta posición.", title: "asco", id: 91 },
  { description: "A nadie más no le gusta el logo de óptica este año. Los 2 verdes se ven horribles", title: "asco", id: 92 },
  { description: "Eso fue un tiro terriblemente abierto...", title: "asco", id: 93 },
  {
    description:
      "que esta comparación ridícula es tan detallada y explícita que me hace pensar que toda la paliza-una-pequeña-cosa es parte de sus fantasías sexuales repugnantes.",
    title: "asco",
    id: 94,
  },
  {
    description:
      "El Valium/Diazepam es mucho más agradable que el Alprazolam/Xanax OMI. Me encanta la relajación muscular. Se siente tan bien, combinado con un opiáceos, ",
    title: "serenidad",
    id: 95,
  },
  { description: "> Alégrate de que no besara a mamá [NAME]. Eso sería una buena historia.", title: "serenidad", id: 96 },
  {
    description: "Me alegro de que estés a salvo. Parecen condiciones heladas, también, por lo que es genial que hayas sido capaz de evitar esto.",
    title: "serenidad",
    id: 97,
  },
  {
    description: "Me alegro de que tus expectativas sean bajas. Estoy esperando reacciones de tirones de rodillas si el juego no va bien esta noche.",
    title: "serenidad",
    id: 98,
  },
  { description: "Esta misma cosa me diagnosticó como ADD. Ahora soy de las drogas y me siento mucho mejor.", title: "serenidad", id: 99 },
  {
    description: "Soy el orgulloso dueño de una camiseta de Vernon Gholston. Mi esposa me lo compró como regalo de Navidad nuestro primer año de citas...",
    title: "aprobacion",
    id: 100,
  },
  { description: "Orgulloso de ti por estar expuesto a todo esto y todavía reconociendo lo loca que es esta mierda.", title: "aprobacion", id: 101 },
  {
    description: "Alabado sea [NAME]. Espero que sus problemas de salud hayan mejorado. Amigo debe estar en un contendiente en este momento ",
    title: "aprobacion",
    id: 102,
  },
  { description: "Orgulloso de mi senador hoy", title: "aprobacion", id: 103 },
  { description: "Todavía ganó la carrera aunque ha que es un fracaso ahora", title: "aprobacion", id: 104 },
  { description: "Asustar intencionadamente a la Reina es un delito inculpable. (máximo 14 años) Código Penal", title: "vigilancia", id: 105 },
  { description: "El único retraso de vuelo que he tenido en slc es porque hubo demasiada lluvia en lax", title: "vigilancia", id: 106 },
  { description: "Esto es lo más aterrador que creo que he leído aquí. Eso es tan horrible.", title: "vigilancia", id: 107 },
  {
    description: "Hoy en día me pongo nervioso viendo defensa de Steelers. En ese entonces, no podía esperar a ver lo que harían a continuación.",
    title: "vigilancia",
    id: 108,
  },
  { description: "Tuve un ataque de pánico cuando vi eso, pensando que dormía durante 3 años y Hall era un pato.", title: "vigilancia", id: 109 },
  { description: "", title: "neutral", id: 110 },
  { description: "Sentimiento de indignación que causa enojo.", title: "ira", id: 111 },
  { description: "Recelo o aprensión que alguien tiene de que le suceda algo contrario a lo que desea.", title: "miedo", id: 112 },
  { description: "Tendencia a actuar o a responder violentamente.", title: "agresidad", id: 113 },
  { description: "Acción y efecto de sorprender.", title: "sorpresa", id: 114 },
  { description: "Propensión a ver y juzgar las cosas en su aspecto más favorable.", title: "optimismo", id: 115 },
  { description: " Acción de admirar.", title: "admiración", id: 116 },
  { description: "Desviación de la atención en algo, entretenimiento o diversión.", title: "distracion", id: 117 },
  { description: "Sentimiento grato y vivo que suele manifestarse con signos exteriores.", title: "alegria", id: 118 },
  {
    description: "Sentimiento intenso del ser humano que, partiendo de su propia insuficiencia, necesita y busca el encuentro y unión con otro ser.",
    title: "amor",
    id: 119,
  },
  { description: "Inquietud, pesar interno que queda después de realizar lo que se considera una mala acción.", title: "remordimiento", id: 120 },
  { description: "Esperanza firme que se tiene de alguien o algo.", title: "confianza", id: 121 },
  { description: "Pesar causado por un desengaño.", title: "decepcion", id: 122 },
  { description: "Sentimiento grande de tristeza.", title: "pena", id: 123 },
  { description: "Cualidad de triste.", title: "tristeza", id: 124 },
  { description: "Provecho, utilidad, ganancia.", title: "interes", id: 125 },
  { description: "Estado placentero de exaltación emocional y admirativa.", title: "extasis", id: 126 },
  { description: "Gran admiración o extrañeza.", title: "asombro", id: 127 },
  { description: "Alteración del estómago causada por la repugnancia que se tiene a algo que incita a vómito.", title: "asco", id: 128 },
  { description: "Cualidad de sereno.", title: "serenidad", id: 129 },
  { description: "Acción y efecto de aprobar.", title: "aprobacion", id: 130 },
  { description: "Cuidado y atención exacta en las cosas que están a cargo de cada uno.", title: "vigilancia", id: 131 },
];

export default emotionalStates;
