const emotionalStates = [
  { id: 1, title: "very-euphoric", description: "Intense feeling of happiness and enthusiasm, almost to the point of excitement." },
  { id: 2, title: "optimistic", description: "Positive and hopeful attitude towards the future." },
  { id: 3, title: "happy", description: "General feeling of well-being and satisfaction." },
  { id: 4, title: "neutral", description: "Emotional stability, without significant highs or lows." },
  { id: 5, title: "indifferent", description: "Lack of emotion or interest, neither happy nor sad." },
  { id: 6, title: "apathetic", description: "Lack of motivation or interest, feeling of disconnection." },
  { id: 7, title: "sad", description: "Feeling of discouragement and unhappiness." },
  { id: 8, title: "desperate", description: "Feeling of anguish and hopelessness, often with anxiety." },
  { id: 9, title: "very-depressed", description: "Intense feelings of sadness, hopelessness, and worthlessness." },
  { id: 10, title: "extremely-depressed", description: "Overwhelming feelings of sadness and hopelessness, potentially dangerous." },
  { id: 11, title: "nervous", description: "Feeling of restlessness and tension, often with anxiety." },
  { id: 12, title: "relaxed", description: "Feeling of calm and tranquility, without stress." },
  { id: 13, title: "exasperated", description: "Intense irritation and frustration." },
  { id: 14, title: "confused", description: "Disorientation and uncertainty, lack of clarity." },
  { id: 15, title: "motivated", description: "High level of energy and focus towards a goal or task." },
  { id: 16, title: "demotivated", description: "Lack of interest or enthusiasm for doing things, feeling of discouragement." },
  { id: 17, title: "aggressive", description: "Tendency to hostility or violent behaviors." },
  { id: 18, title: "passive", description: "Lack of energy or interest in actively participating in situations." },
  { id: 19, title: "excited", description: "Feeling of joy and anticipation for a future event or situation." },
  { id: 20, title: "discouraged", description: "Feeling of hopelessness and lack of confidence." },
  { id: 21, title: "overwhelmed", description: "Feeling of being swamped and unable to handle current demands or situations." },
  { id: 22, title: "hopeful", description: "Optimism and confidence in a better future or in the success of something." },
  { id: 23, title: "distrustful", description: "Feeling of suspicion or lack of trust in other people or situations." },
  { id: 24, title: "insecure", description: "Lack of confidence in oneself or one's abilities." },
  { id: 25, title: "proud", description: "Satisfaction in oneself or one's achievements." },
  { id: 26, title: "ashamed", description: "Feeling of humiliation or shame for something done." },
  { id: 27, title: "grateful", description: "Feeling of gratitude and appreciation towards someone or something." },
  { id: 28, title: "resentful", description: "Bitterness or anger over something considered unfair or offensive." },
  { id: 29, title: "impatient", description: "Lack of patience, desire for something to happen immediately." },
  { id: 30, title: "serene", description: "Calm and tranquility, often after a period of agitation or uncertainty." }
];

export default emotionalStates;  