const emotionalStates = [
  { title: "neutral", description: "Sin sintemiento aparente.", id: 0 },
  { title: "alegria", description: "Alegría.Emoción positiva. Estado de bienestar y satisfacción respecto a uno mismo y/o las condiciones generales de la vida.", id: 8 },
  { title: "miedo", description: "Miedo. Nerviosismo. Recelo o aprensión que alguien tiene de que le suceda algo contrario a lo que desea.", id: 2 },
  { title: "confianza", description: "Confianza. Esperanza firme que se tiene de alguien o algo.", id: 11 },
  { title: "sorpresa", description: "Acción y efecto de sorprender.", id: 4 },
  { title: "tristeza", description: "Trsiteza. Cualidad de triste, agobio, desesperanza", id: 14 },
  { title: "asco", description: "Asco. Alteración del estómago causada por la repugnancia que se tiene a algo que incita a vómito.", id: 18 },
  { title: "ira", description: "Ira. Enfado. Sentimiento de indignación que causa enojo.Rábia a alguien", id: 1 },
  { title: "vigilancia", description: "Vigiláncia. Cuidado y atención exacta en las cosas que están a cargo de cada uno.", id: 21 },
  // { title: "agresidad", description: "Tendencia a actuar o a responder violentamente.", id: 3 },
  // { title: "optimismo", description: "Propensión a ver y juzgar las cosas en su aspecto más favorable.", id: 5 },
  // { title: "admiracion", description: "Admiración. Acción de admirar.", id: 6 },
  // { title: "distracion", description: "Desviación de la atención en algo, entretenimiento o diversión.", id: 7 },
  // { title: "extasis", description: "Estado placentero de exaltación emocional y gozo extremo.", id: 16 },
  // {
  //   title: "amor",
  //   description: "Sentimiento intenso del ser humano que, partiendo de su propia insuficiencia, necesita y busca el encuentro y unión con otro ser.",
  //   id: 9,
  // },
  // { title: "remordimiento", description: "Inquietud, pesar interno que queda después de realizar lo que se considera una mala acción.", id: 10 },
  // { title: "decepcion", description: "Pena causado por un desengaño, u observar que alguien no tiene el comportameniento deseado", id: 12 },
  // { title: "pena", description: "Sentimiento grande de tristeza.", id: 13 },
  // { title: "interes", description: "sensación de curiosidad que una persona siente hacia algo o alguien.", id: 15 },
  // { title: "asombro", description: "Reacción de sorpresa intensa ante algo inesperado.", id: 17 },
  // { title: "serenidad", description: "Cualidad de sereno.", id: 19 },
  // { title: "aprobacion", description: "Acción y efecto de aprobar.", id: 20 },
];
export default emotionalStates;  