const emotionalStates = [
  { title: "neutral", description: "Sin sintemiento aparente.", id: 0 },
  { title: "ira", description: "Sentimiento de indignación que causa enojo.Rábia a alguien", id: 1 },
  { title: "miedo", description: "Recelo o aprensión que alguien tiene de que le suceda algo contrario a lo que desea.", id: 2 },
  { title: "agresidad", description: "Tendencia a actuar o a responder violentamente.", id: 3 },
  { title: "sorpresa", description: "Acción y efecto de sorprender.", id: 4 },
  { title: "optimismo", description: "Propensión a ver y juzgar las cosas en su aspecto más favorable.", id: 5 },
  { title: "admiracion", description: " Acción de admirar.", id: 6 },
  { title: "distracion", description: "Desviación de la atención en algo, entretenimiento o diversión.", id: 7 },
  { title: "alegria", description: "Sentimiento grato y vivo que suele manifestarse con signos exteriores.", id: 8 },
  {
    title: "amor",
    description: "Sentimiento intenso del ser humano que, partiendo de su propia insuficiencia, necesita y busca el encuentro y unión con otro ser.",
    id: 9,
  },
  { title: "remordimiento", description: "Inquietud, pesar interno que queda después de realizar lo que se considera una mala acción.", id: 10 },
  { title: "confianza", description: "Esperanza firme que se tiene de alguien o algo.", id: 11 },
  { title: "decepcion", description: "Pena causado por un desengaño, u observar que alguien no tiene el comportameniento deseado", id: 12 },
  { title: "pena", description: "Sentimiento grande de tristeza.", id: 13 },
  { title: "tristeza", description: "Cualidad de triste, agobio, desesperanza", id: 14 },
  { title: "interes", description: "sensación de curiosidad o preocupación que una persona siente hacia algo o alguien.", id: 15 },
  { title: "extasis", description: "Estado placentero de exaltación emocional y admirativa.", id: 16 },
  { title: "asombro", description: "Gran admiración o extrañeza.", id: 17 },
  { title: "asco", description: "Alteración del estómago causada por la repugnancia que se tiene a algo que incita a vómito.", id: 18 },
  { title: "serenidad", description: "Cualidad de sereno.", id: 19 },
  { title: "aprobacion", description: "Acción y efecto de aprobar.", id: 20 },
  { title: "vigilancia", description: "Cuidado y atención exacta en las cosas que están a cargo de cada uno.", id: 21 },
];
export default emotionalStates;  